apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: resttemplateserver-sep
  newName: 210.90.24.172:8080/camit/yklee2002/resttemplateserver-sep
  newTag: c10bd1e89eaba006eda39ffc8dc75ccf6aeeb2d4
