apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: resttemplateserver-sep
  newName: 210.90.24.172:8080/camit/yklee2002/resttemplateserver-sep
  newTag: 512ea5e7896e6790ff7d650d5e98b5b8bf62b3b7
