apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
- name: resttemplateserver-sep
  newName: 210.90.24.172:8080/camit/yklee2002/resttemplateserver-sep
  newTag: latest
